/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayLayoutRouteImport } from './routes/display/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as DisplayLayoutIndexRouteImport } from './routes/display/_layout/index'
import { Route as DisplayLayoutRoomIdRouteImport } from './routes/display/_layout/$roomId'
import { Route as AdminLayoutRoomsIndexRouteImport } from './routes/admin/_layout/rooms/index'
import { Route as AdminLayoutRoomsRoomIdRouteImport } from './routes/admin/_layout/rooms/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayLayoutRoute = DisplayLayoutRouteImport.update({
  id: '/display/_layout',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayLayoutIndexRoute = DisplayLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisplayLayoutRoute,
} as any)
const DisplayLayoutRoomIdRoute = DisplayLayoutRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => DisplayLayoutRoute,
} as any)
const AdminLayoutRoomsIndexRoute = AdminLayoutRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutRoomsRoomIdRoute = AdminLayoutRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display': typeof DisplayLayoutRouteWithChildren
  '/display/$roomId': typeof DisplayLayoutRoomIdRoute
  '/display/': typeof DisplayLayoutIndexRoute
  '/admin/rooms/$roomId': typeof AdminLayoutRoomsRoomIdRoute
  '/admin/rooms/': typeof AdminLayoutRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display/$roomId': typeof DisplayLayoutRoomIdRoute
  '/display': typeof DisplayLayoutIndexRoute
  '/admin/rooms/$roomId': typeof AdminLayoutRoomsRoomIdRoute
  '/admin/rooms': typeof AdminLayoutRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display/_layout': typeof DisplayLayoutRouteWithChildren
  '/display/_layout/$roomId': typeof DisplayLayoutRoomIdRoute
  '/display/_layout/': typeof DisplayLayoutIndexRoute
  '/admin/_layout/rooms/$roomId': typeof AdminLayoutRoomsRoomIdRoute
  '/admin/_layout/rooms/': typeof AdminLayoutRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/display'
    | '/display/$roomId'
    | '/display/'
    | '/admin/rooms/$roomId'
    | '/admin/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/display/$roomId'
    | '/display'
    | '/admin/rooms/$roomId'
    | '/admin/rooms'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/display/_layout'
    | '/display/_layout/$roomId'
    | '/display/_layout/'
    | '/admin/_layout/rooms/$roomId'
    | '/admin/_layout/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  DisplayLayoutRoute: typeof DisplayLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/_layout': {
      id: '/display/_layout'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/_layout/': {
      id: '/display/_layout/'
      path: '/'
      fullPath: '/display/'
      preLoaderRoute: typeof DisplayLayoutIndexRouteImport
      parentRoute: typeof DisplayLayoutRoute
    }
    '/display/_layout/$roomId': {
      id: '/display/_layout/$roomId'
      path: '/$roomId'
      fullPath: '/display/$roomId'
      preLoaderRoute: typeof DisplayLayoutRoomIdRouteImport
      parentRoute: typeof DisplayLayoutRoute
    }
    '/admin/_layout/rooms/': {
      id: '/admin/_layout/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AdminLayoutRoomsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/rooms/$roomId': {
      id: '/admin/_layout/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/admin/rooms/$roomId'
      preLoaderRoute: typeof AdminLayoutRoomsRoomIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutRoomsRoomIdRoute: typeof AdminLayoutRoomsRoomIdRoute
  AdminLayoutRoomsIndexRoute: typeof AdminLayoutRoomsIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutRoomsRoomIdRoute: AdminLayoutRoomsRoomIdRoute,
  AdminLayoutRoomsIndexRoute: AdminLayoutRoomsIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface DisplayLayoutRouteChildren {
  DisplayLayoutRoomIdRoute: typeof DisplayLayoutRoomIdRoute
  DisplayLayoutIndexRoute: typeof DisplayLayoutIndexRoute
}

const DisplayLayoutRouteChildren: DisplayLayoutRouteChildren = {
  DisplayLayoutRoomIdRoute: DisplayLayoutRoomIdRoute,
  DisplayLayoutIndexRoute: DisplayLayoutIndexRoute,
}

const DisplayLayoutRouteWithChildren = DisplayLayoutRoute._addFileChildren(
  DisplayLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  DisplayLayoutRoute: DisplayLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
