/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayLayoutRouteImport } from './routes/display/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as DisplayLayoutIndexRouteImport } from './routes/display/_layout/index'
import { Route as DisplayLayoutTimerIdRouteImport } from './routes/display/_layout/$timerId'
import { Route as AdminLayoutTimersIndexRouteImport } from './routes/admin/_layout/timers/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayLayoutRoute = DisplayLayoutRouteImport.update({
  id: '/display/_layout',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayLayoutIndexRoute = DisplayLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisplayLayoutRoute,
} as any)
const DisplayLayoutTimerIdRoute = DisplayLayoutTimerIdRouteImport.update({
  id: '/$timerId',
  path: '/$timerId',
  getParentRoute: () => DisplayLayoutRoute,
} as any)
const AdminLayoutTimersIndexRoute = AdminLayoutTimersIndexRouteImport.update({
  id: '/timers/',
  path: '/timers/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display': typeof DisplayLayoutRouteWithChildren
  '/display/$timerId': typeof DisplayLayoutTimerIdRoute
  '/display/': typeof DisplayLayoutIndexRoute
  '/admin/timers/': typeof AdminLayoutTimersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display/$timerId': typeof DisplayLayoutTimerIdRoute
  '/display': typeof DisplayLayoutIndexRoute
  '/admin/timers': typeof AdminLayoutTimersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display/_layout': typeof DisplayLayoutRouteWithChildren
  '/display/_layout/$timerId': typeof DisplayLayoutTimerIdRoute
  '/display/_layout/': typeof DisplayLayoutIndexRoute
  '/admin/_layout/timers/': typeof AdminLayoutTimersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/display'
    | '/display/$timerId'
    | '/display/'
    | '/admin/timers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/display/$timerId'
    | '/display'
    | '/admin/timers'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/display/_layout'
    | '/display/_layout/$timerId'
    | '/display/_layout/'
    | '/admin/_layout/timers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  DisplayLayoutRoute: typeof DisplayLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/_layout': {
      id: '/display/_layout'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/_layout/': {
      id: '/display/_layout/'
      path: '/'
      fullPath: '/display/'
      preLoaderRoute: typeof DisplayLayoutIndexRouteImport
      parentRoute: typeof DisplayLayoutRoute
    }
    '/display/_layout/$timerId': {
      id: '/display/_layout/$timerId'
      path: '/$timerId'
      fullPath: '/display/$timerId'
      preLoaderRoute: typeof DisplayLayoutTimerIdRouteImport
      parentRoute: typeof DisplayLayoutRoute
    }
    '/admin/_layout/timers/': {
      id: '/admin/_layout/timers/'
      path: '/timers'
      fullPath: '/admin/timers/'
      preLoaderRoute: typeof AdminLayoutTimersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutTimersIndexRoute: typeof AdminLayoutTimersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutTimersIndexRoute: AdminLayoutTimersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface DisplayLayoutRouteChildren {
  DisplayLayoutTimerIdRoute: typeof DisplayLayoutTimerIdRoute
  DisplayLayoutIndexRoute: typeof DisplayLayoutIndexRoute
}

const DisplayLayoutRouteChildren: DisplayLayoutRouteChildren = {
  DisplayLayoutTimerIdRoute: DisplayLayoutTimerIdRoute,
  DisplayLayoutIndexRoute: DisplayLayoutIndexRoute,
}

const DisplayLayoutRouteWithChildren = DisplayLayoutRoute._addFileChildren(
  DisplayLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  DisplayLayoutRoute: DisplayLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
